// Musa Özkan 150121058 
// This class simply creates item objects 
public class Item { // represents an item generated by the employees working for the factory.
	private int id; // id of the Item object created.
	static int numberOfItems; // keeps the number of item objects created.
	// Constructor to create Item objects
	Item(int id){
		this.id=id;
		numberOfItems++;
	}	
}
